//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Duplicate of the opencode structs from theme.go so this generator is standalone.
type ocVariant struct {
	Palette struct {
		Neutral     string `json:"neutral"`
		Ink         string `json:"ink"`
		Primary     string `json:"primary"`
		Accent      string `json:"accent,omitempty"`
		Success     string `json:"success"`
		Warning     string `json:"warning"`
		Error       string `json:"error"`
		Info        string `json:"info"`
		Interactive string `json:"interactive,omitempty"`
		DiffAdd     string `json:"diffAdd,omitempty"`
		DiffDelete  string `json:"diffDelete,omitempty"`
	} `json:"palette"`
	Overrides map[string]string `json:"overrides"`
}

type ocThemeFile struct {
	Name  string    `json:"name"`
	ID    string    `json:"id"`
	Light ocVariant `json:"light"`
	Dark  ocVariant `json:"dark"`
}

type themeColor struct {
	User, Assistant, Header, Border, Hint, Text, Background string
	StatusBg, StatusFg, SelectedFg, SelectedBg              string
	Success, Error, Accent, Dim, Thinking                   string
}

func first(vals ...string) string {
	for _, s := range vals {
		if s != "" {
			return s
		}
	}
	return "#000000"
}

func convert(v ocVariant) themeColor {
	p := v.Palette
	o := v.Overrides
	textWeak := first(o["text-weak"], o["syntax-comment"], p.Ink)
	syntaxComment := first(o["syntax-comment"], o["text-weak"], p.Ink)
	borderColor := first(o["syntax-comment"], o["text-weak"])
	if borderColor == "" || borderColor == p.Neutral {
		borderColor = syntaxComment
	}
	return themeColor{
		User:       p.Primary,
		Assistant:  first(p.Accent, o["syntax-keyword"], p.Info),
		Header:     first(p.Info, p.Primary, p.Warning),
		Border:     borderColor,
		Hint:       textWeak,
		Text:       p.Ink,
		Background: p.Neutral,
		StatusBg:   p.Neutral,
		StatusFg:   textWeak,
		SelectedFg: p.Neutral,
		SelectedBg: p.Primary,
		Success:    p.Success,
		Error:      p.Error,
		Accent:     first(p.Accent, o["syntax-constant"], p.Info),
		Dim:        borderColor,
		Thinking:   textWeak,
	}
}

// themes already present in ocode's builtinThemes (dark variant names).
// builtinThemes lives in internal/theme; the generated output (the map body
// printed below) is written to internal/theme/theme_generated.go.
var existing = map[string]bool{
	"tokyonight":       true,
	"tokyonight-storm": true,
	"opencode":         true,
	"flexoki":          true,
	"one-dark":         true,
	"gruvbox":          true,
	"onedark":          true,
	"nord":             true,
	"kanagawa":         true,
	"catppuccin-mocha": true,
	"catppuccin-latte": true,
	"dracula":          true,
	"solarized":        true,
	"github-dark":      true,
	"github-light":     true,
	"everforest":       true,
	// light variants that already exist
	"opencode-light":   true,
	"gruvbox-light":    true,
	"nord-light":       true,
	"solarized-light":  true,
	"everforest-light": true,
	// ocode-exclusive themes (not from opencode theme registry)
	"pipboy": true,
	"lcars":  true,
}

func quote(s string) string {
	return fmt.Sprintf("%q", s)
}

func main() {
	srcDir := "."
	if len(os.Args) > 1 {
		srcDir = os.Args[1]
	}

	entries, err := os.ReadDir(srcDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading directory %s: %v\n", srcDir, err)
		os.Exit(1)
	}

	type genEntry struct {
		name   string
		colors themeColor
	}
	var generated []genEntry

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(srcDir, entry.Name()))
		if err != nil {
			continue
		}

		var oc ocThemeFile
		if err := json.Unmarshal(data, &oc); err != nil {
			continue
		}
		if oc.ID == "" || oc.Dark.Palette.Neutral == "" {
			continue
		}

		// Skip themes that already exist in ocode.
		if !existing[oc.ID] {
			generated = append(generated, genEntry{name: oc.ID, colors: convert(oc.Dark)})
		}
		lightName := oc.ID + "-light"
		if !existing[lightName] && oc.Light.Palette.Neutral != "" {
			generated = append(generated, genEntry{name: lightName, colors: convert(oc.Light)})
		}
	}

	sort.Slice(generated, func(i, j int) bool {
		return generated[i].name < generated[j].name
	})

	fmt.Println("// Code generated by gen_themes; DO NOT EDIT.")
	fmt.Println()
	for _, g := range generated {
		c := g.colors
		fmt.Printf("%q: {\n", g.name)
		fmt.Printf("\t\t\tColors: ThemeColors{\n")
		fmt.Printf("\t\t\t\tUser:       %s,\n", quote(c.User))
		fmt.Printf("\t\t\t\tAssistant:  %s,\n", quote(c.Assistant))
		fmt.Printf("\t\t\t\tHeader:     %s,\n", quote(c.Header))
		fmt.Printf("\t\t\t\tBorder:     %s,\n", quote(c.Border))
		fmt.Printf("\t\t\t\tHint:       %s,\n", quote(c.Hint))
		fmt.Printf("\t\t\t\tText:       %s,\n", quote(c.Text))
		fmt.Printf("\t\t\t\tBackground: %s,\n", quote(c.Background))
		fmt.Printf("\t\t\t\tStatusBg:   %s,\n", quote(c.StatusBg))
		fmt.Printf("\t\t\t\tStatusFg:   %s,\n", quote(c.StatusFg))
		fmt.Printf("\t\t\t\tSelectedFg: %s,\n", quote(c.SelectedFg))
		fmt.Printf("\t\t\t\tSelectedBg: %s,\n", quote(c.SelectedBg))
		fmt.Printf("\t\t\t\tSuccess:    %s,\n", quote(c.Success))
		fmt.Printf("\t\t\t\tError:      %s,\n", quote(c.Error))
		fmt.Printf("\t\t\t\tAccent:     %s,\n", quote(c.Accent))
		fmt.Printf("\t\t\t\tDim:        %s,\n", quote(c.Dim))
		fmt.Printf("\t\t\t},\n")
		fmt.Printf("\t\t},\n")
	}
}
