package server

import (
	"fmt"
	"net/http"
	"os"
	"strconv"

	"github.com/jamesmercstudio/ocode/internal/commands"
	"github.com/jamesmercstudio/ocode/internal/github"
	"github.com/jamesmercstudio/ocode/internal/skill"
)

func (h *Handler) HandleListSkills(w http.ResponseWriter, r *http.Request) {
	statuses, err := skill.GetSkillStatus()
	if err != nil {
		basic := skill.LoadSkills()
		type entry struct {
			Name        string `json:"name"`
			Description string `json:"description"`
		}
		out := make([]entry, len(basic))
		for i, s := range basic {
			out[i] = entry{Name: s.Name, Description: s.Description}
		}
		writeJSON(w, http.StatusOK, out)
		return
	}

	type entry struct {
		Name   string `json:"name"`
		Status string `json:"status"`
		Source string `json:"source,omitempty"`
	}
	out := make([]entry, len(statuses))
	for i, s := range statuses {
		out[i] = entry{Name: s.Name, Status: s.Status.String(), Source: s.Source}
	}
	writeJSON(w, http.StatusOK, out)
}

func (h *Handler) HandleListCommands(w http.ResponseWriter, r *http.Request) {
	cmds := commands.LoadCommands(nil)
	type entry struct {
		Name        string `json:"name"`
		Description string `json:"description,omitempty"`
	}
	out := make([]entry, len(cmds))
	for i, c := range cmds {
		out[i] = entry{Name: c.Name, Description: c.Description}
	}
	writeJSON(w, http.StatusOK, out)
}

func (h *Handler) HandleGitHubPR(w http.ResponseWriter, r *http.Request, owner, repo string, prNumber int) {
	pr, err := github.GetPR(owner, repo, prNumber)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	diff, _ := github.GetPRDiff(owner, repo, prNumber)
	writeJSON(w, http.StatusOK, map[string]any{"pr": pr, "diff": diff})
}

func (h *Handler) HandleGitHubIssues(w http.ResponseWriter, r *http.Request, owner, repo string) {
	state := r.URL.Query().Get("state")
	if state == "" {
		state = "open"
	}
	issues, err := github.ListIssues(owner, repo, state)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, issues)
}

func (h *Handler) HandleInit(w http.ResponseWriter, r *http.Request) {
	const agentsFile = "AGENTS.md"
	if _, err := os.Stat(agentsFile); err == nil {
		writeJSON(w, http.StatusOK, map[string]string{"path": agentsFile, "status": "already exists"})
		return
	}

	wd, _ := os.Getwd()
	content := fmt.Sprintf("# Project\n\n> Auto-generated by ocode. Edit this file to describe your project.\n\n## Working Directory\n\n%s\n", wd)
	if err := os.WriteFile(agentsFile, []byte(content), 0644); err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusCreated, map[string]string{"path": agentsFile, "status": "created"})
}

// parseGitHubPRRoute extracts owner/repo/number path values.
func parseGitHubPRRoute(r *http.Request) (owner, repo string, number int, ok bool) {
	owner = r.PathValue("owner")
	repo = r.PathValue("repo")
	numStr := r.PathValue("number")
	n, err := strconv.Atoi(numStr)
	if owner == "" || repo == "" || err != nil {
		return "", "", 0, false
	}
	return owner, repo, n, true
}
