.\" Man page for ocode web
.TH OCODE-WEB 1 "June 2025" "ocode" "User Commands"
.SH NAME
ocode-web \- Start server and open browser (alias for serve --open)
.SH SYNOPSIS
.B ocode web
[\fIoptions\fR]
.SH DESCRIPTION
Start the HTTP server with web UI and automatically open the browser.
This is a convenience alias for \fBocode serve \-\-open\fR.
.SH OPTIONS
All options from \fBocode serve\fR are supported.
.TP
\fB\-port\fR \fI<port>\fR
Port to listen on (default: 4096).
.TP
\fB\-host\fR \fI<host>\fR
Host to bind to (default: 0.0.0.0).
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message and exit.
.SH EXAMPLES
.TP
Start and open browser:
.B ocode web
.TP
Custom port:
.B ocode web -port 8080
.SH SEE ALSO
.BR ocode-serve (1),
.BR ocode (1)